### ISSUE TITLE
php-sql-creator: operators in functions throw error

### ISSUE THREAD

**Issue by witchi** [greenlion/PHP-SQL-Parser#102]
_From [adrian.p...@googlemail.com](https://code.google.com/u/116057851280130181832/) on October 18, 2012 11:47:53_

Having operators in functions and aggregates throws an

UnableToCreateSQLException

in PHPSQLCreator->processFunction.

Solution:

Add 

                $sql .= $this->processOperator($v);

at line 410 ( r346 ).

_Original issue: http://code.google.com/p/php-sql-parser/issues/detail?id=76_

**Comment by witchi** [comment]
_From [adrian.p...@googlemail.com](https://code.google.com/u/116057851280130181832/) on October 18, 2012 04:12:08_

It should actually be something like this (in order to get the separation of the variable list with the commas correct)

add:

        protected function isOperator($parsed) {
            return ($parsed['expr_type'] === ExpressionType::OPERATOR);
        }

and change from line 405 ( r346 ) onwards to:
            foreach ($parsed['sub_tree'] as $k => $v) {
                $len = strlen($sql);
                $sql .= $this->processFunction($v);
                $sql .= $this->processConstant($v);
                $sql .= $this->processColRef($v);
                $sql .= $this->processReserved($v);
                
                if($this->isOperator($v)) {
                    $sql = substr($sql, 0, -1) . " " . $this->processOperator($v);
                }
                
                if ($len == strlen($sql)) {
                   throw new UnableToCreateSQLException('function subtree', $k, $v, 'expr_type');
                }

                $sql .= ($this->isReserved($v) || $this->isOperator($v) ? " " : ",");
            }


                $sql .= ($this->isReserved($v) ? " " : ",");

to

                if($this->isOperator($v)) {
                    $sql = substr($sql, 0, -1) . " ";
                } else {
                    $sql .= ($this->isReserved($v) ? " " : ",");
                }

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on October 23, 2013 01:37:38_

Can you specify a short example? I could use it as test case.

**Comment by witchi** [comment]
_From [adrian.p...@googlemail.com](https://code.google.com/u/116057851280130181832/) on October 23, 2013 05:10:45_

Sure. The following SQL query parsed and then recreated throws the error:

SELECT AVG(2.0 * foo) FROM bar;

Error:

PHP Fatal error:  Uncaught exception 'UnableToCreateSQLException' with message 'unknown expr_type in function subtree[1] operator' in /home/adrpar/tmp/php-sql-parser-read-only/php-sql-creator.php:419
Stack trace:
\#0 /home/adrpar/tmp/php-sql-parser-read-only/php-sql-creator.php(125): PHPSQLCreator->processFunction(Array)
\#1 /home/adrpar/tmp/php-sql-parser-read-only/php-sql-creator.php(73): PHPSQLCreator->processSELECT(Array)
\#2 /home/adrpar/tmp/php-sql-parser-read-only/php-sql-creator.php(54): PHPSQLCreator->processSelectStatement(Array)
\#3 /home/adrpar/tmp/php-sql-parser-read-only/example.php(22): PHPSQLCreator->create(Array)
\#4 {main}
  thrown in /home/adrpar/tmp/php-sql-parser-read-only/php-sql-creator.php on line 419

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on October 23, 2013 09:00:39_

I try to handle that with an additional expression part. The parser doesn't generate a good output for the case 

SELECT ABC(2.0 * foo, x) FROM bar

So, it seems to be better to look into the parameters.

**Status:** Started

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on October 24, 2013 14:17:52_

rev 374 should fix that issue.

**Status:** Fixed  
  **Owner:** pho...@gmx.de
