### ISSUE TITLE
Problems creating query with some operators/functions

### ISSUE THREAD

**Issue by witchi** [greenlion/PHP-SQL-Parser#115]
_From [davide.i...@gmail.com](https://code.google.com/u/109298735041990463307/) on February 15, 2013 23:41:02_

What steps will reproduce the problem? I'm trying to parse, modify and recreate a query.

1. Query:

$sql = "select ut.id, ut.numero_cartella, ut.nome, ut.cognome, floor(DATEDIFF(de.`data`,ut.data_di_nascita)/365) as eta,
sx.valore as sesso, cd.valore as diagnosi_prevalente, co.valore as consapevolezza,
DATEDIFF(de.`data`,az.data_inizio_assistenza) as durata_assistenza_giorni, ld.valore as luogo_decesso,
ca.valore as carico_assistenza, if(sa.id is null, null,if(sa.fkey_cod_care_giver_interno__con_chi_vive=1,'si','no')) as vive_solo,
sn.valore as oltre_70
from gen_cms_utenti ut";

2. Parse

$parser = new PHPSQLParser();
$parser->parse($sql);

3. Create query from the parsed query

$creator = new PHPSQLCreator();
$creator->create($parser->parsed); 
$save = $creator->created; What is the expected output? What do you see instead? Expected output: the original query.

What I see instead:
Uncaught exception 'UnableToCreateSQLException' with message 'unknown expr_type in function subtree[1] operator' in C:\xampp\htdocs\php-sql-creator.php:416
Stack trace:
\#0 C:\xampp\htdocs\php-sql-creator.php(120): PHPSQLCreator-&gt;processFunction(Array)
\#1 C:\xampp\htdocs\php-sql-creator.php(72): PHPSQLCreator-&gt;processSELECT(Array)
\#2 C:\xampp\htdocs\php-sql-creator.php(53): PHPSQLCreator-&gt;processSelectStatement(Array)
\#3 C:\xampp\htdocs\test.php(53): PHPSQLCreator-&gt;create(Array)
\#4 {main}
  thrown in \<b>C:\xampp\htdocs\php-sql-creator.php on line 416 What version of the product are you using? On what operating system? php-sql-parser-20120822 on Windows 7 64bit Please provide any additional information below. I tried to comment the throw instruction in the php-sql-creator.php file(line 416) and this is the output (if it can help):

SELECT ut.id,ut.numero_cartella,ut.nome,ut.cognome,floor(DATEDIFF(de.`data`,ut.data_di_nascita),,365),sx.valore as sesso,cd.valore as diagnosi_prevalente,co.valore as consapevolezza,DATEDIFF(de.`data`,az.data_inizio_assistenza),ld.valore as luogo_decesso,ca.valore as carico_assistenza,if(sa.id,,null,null,if(sa.fkey_cod_care_giver_interno__con_chi_vive,,1,'si','no')),sn.valore as oltre_70 FROM gen_cms_utenti ut 

Original Query                     Recreated Query
     "/"                 ->              ",,"
   "as eta"              ->            nothing
"[...]vive=1,'si','no'"  ->      "[...]vive,,1,'si','no'"

_Original issue: http://code.google.com/p/php-sql-parser/issues/detail?id=89_

**Comment by witchi** [comment]
_From [davide.i...@gmail.com](https://code.google.com/u/109298735041990463307/) on February 15, 2013 17:23:55_

Partial Solution:
In php-sql-creator.php:
	1) Added the function:
	
		protected function isOperator($parsed) {
			return ($parsed['expr_type'] === 'operator');
		}
		
	2) Modified processFunction($parsed) adding:
		if($this->isOperator($v)) {
		        $sql = substr($sql, 0, -1) . " " . $this->processOperator($v);
		}

**Comment by witchi** [comment]
_From [davide.i...@gmail.com](https://code.google.com/u/109298735041990463307/) on February 16, 2013 02:33:16_

The problem with the aliases was solved in the issue #77 : https://code.google.com/p/php-sql-parser/issues/detail?id=77

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on October 24, 2013 14:49:11_

I think, this issue has been fixed. Check r380 .

**Status:** Fixed
