### ISSUE TITLE
DISTINCT causes error in PHPSQLCreator

### ISSUE THREAD

**Issue by witchi** [greenlion/PHP-SQL-Parser#136]
_From [noisecap...@gmail.com](https://code.google.com/u/104089814064537247718/) on January 03, 2014 21:52:32_

The DISTINCT keyword doesn't appear to be handled in the PHPSQLCreator. An exception is thrown instead.

This code reproduces the problem:
$parser = new PHPSQLParser();
$creator = new PHPSQLCreator();

$tree = $parser->parse("SELECT DISTINCT a FROM b");
print($creator->create($tree));

Stack trace:
PHP Fatal error:  Uncaught exception 'UnableToCreateSQLException' with message 'unknown expr_type in SELECT[0] reserved' in /home/george/Projects/svn/php-sql-parser-read-only/src/builders/SelectBuilder.php:94
Stack trace:
\#0 /home/george/Projects/svn/php-sql-parser-read-only/src/builders/SelectStatementBuilder.php(61): SelectBuilder->build(Array)
\#1 /home/george/Projects/svn/php-sql-parser-read-only/src/builders/SelectStatementBuilder.php(90): SelectStatementBuilder->buildSELECT(Array)
\#2 /home/george/Projects/svn/php-sql-parser-read-only/src/PHPSQLCreator.php(75): SelectStatementBuilder->build(Array)
\#3 /home/george/Projects/svn/php-sql-parser-read-only/test.php(13): PHPSQLCreator->create(Array)
\#4 {main}
  thrown in /home/george/Projects/svn/php-sql-parser-read-only/src/builders/SelectBuilder.php on line 94

This was run against the latest in SVN, but the error happens with the latest download as well (php-sql-parser-20131130.zip)

Would it be sufficient to do something like this?

function processReserved($parsed) {
            if ($parsed['expr_type'] !== ExpressionType::RESERVED) {
                return "";
            }
            $sql = $parsed['base_expr'];
            return $sql;
}

_Original issue: http://code.google.com/p/php-sql-parser/issues/detail?id=110_

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on January 06, 2014 00:28:00_

I have changed some things for SELECT options like DISTINCT within the parser. The r897 handles the reserved keywords within the select clause, but there is a comma behind the DISTINCT within the generated SQL statement. The parser must be enhanced to create a new output property, which holds the concatenation character.

**Status:** Accepted

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on January 06, 2014 01:47:26_

Fixed in r901 .

**Status:** Fixed  
  **Owner:** pho...@gmx.de

**Comment by witchi** [comment]
_From [noisecap...@gmail.com](https://code.google.com/u/104089814064537247718/) on January 06, 2014 08:04:56_

Thanks for your quick response!
