### ISSUE TITLE
Problem parsing group by alias

### ISSUE THREAD

**Issue by witchi** [greenlion/PHP-SQL-Parser#144]
_From [noisecap...@gmail.com](https://code.google.com/u/104089814064537247718/) on January 29, 2014 19:31:24_

To reproduce:
$sql = "select organism_name as reference from organisms group by reference";
$parser = new PHPSQLParser();
$creator = new PHPSQLCreator();
$tree = $parser->parse($sql);
var_dump($creator->create($tree));

The last line causes this exception:
PHP Warning:  Uncaught exception 'UnableToCreateSQLException' with message 'unknown [expr_type] = alias in "GROUP" [0] ' in /home/george/Projects/svn/php-sql-parser-read-only/src/builders/GroupByBuilder.php:82
Stack trace:
\#0 /home/george/Projects/svn/php-sql-parser-read-only/src/builders/SelectStatementBuilder.php(77): GroupByBuilder->build(Array)
\#1 /home/george/Projects/svn/php-sql-parser-read-only/src/builders/SelectStatementBuilder.php(104): SelectStatementBuilder->buildGROUP(Array)
\#2 /home/george/Projects/svn/php-sql-parser-read-only/src/PHPSQLCreator.php(75): SelectStatementBuilder->build(Array)
\#3 php shell code(1): PHPSQLCreator->create(Array)
\#4 {main}
  thrown in /home/george/Projects/svn/php-sql-parser-read-only/src/builders/GroupByBuilder.php on line 82

Thanks,
-George

_Original issue: http://code.google.com/p/php-sql-parser/issues/detail?id=118_

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on January 30, 2014 02:29:41_

The issue has been fixed, see r1055

**Status:** Fixed  
  **Owner:** pho...@gmx.de

**Comment by witchi** [comment]
_From [noisecap...@gmail.com](https://code.google.com/u/104089814064537247718/) on January 30, 2014 08:20:28_

I can confirm this, thanks for your efforts!
