### ISSUE TITLE
Support for expressions in ORDER BY clause

### ISSUE THREAD

**Issue by witchi** [greenlion/PHP-SQL-Parser#167]
_From [noisecap...@gmail.com](https://code.google.com/u/104089814064537247718/) on May 22, 2014 17:52:47_

This works fine:
SELECT f FROM t ORDER BY f-0.0

But this fails on create:
SELECT f FROM t ORDER BY (f-0.0)

This isn't a problem for me since the first statement works fine, just something I noticed.

To reproduce, I wrote this script:

require_once "src/PHPSQLParser/PHPSQLParser.php";
require_once "src/PHPSQLParser/PHPSQLCreator.php";
$parser = new PHPSQLParser\PHPSQLParser();
$creator = new PHPSQLParser\PHPSQLCreator();
$x = $parser->parse("SELECT f FROM t ORDER BY (f-0.0)");
var_dump($creator->create($x));

Stack trace:
PHP Fatal error:  Uncaught exception 'PHPSQLParser\exceptions\UnableToCreateSQLException' with message 'unknown [expr_type] = bracket_expression in "ORDER" [0] ' in /home/george/Projects/git/PHP-SQL-Parser/src/PHPSQLParser/builders/OrderByBuilder.php:100
Stack trace:
\#0 /home/george/Projects/git/PHP-SQL-Parser/src/PHPSQLParser/builders/SelectStatementBuilder.php(89): PHPSQLParser\builders\OrderByBuilder->build(Array)
\#1 /home/george/Projects/git/PHP-SQL-Parser/src/PHPSQLParser/builders/SelectStatementBuilder.php(115): PHPSQLParser\builders\SelectStatementBuilder->buildORDER(Array)
\#2 /home/george/Projects/git/PHP-SQL-Parser/src/PHPSQLParser/PHPSQLCreator.php(90): PHPSQLParser\builders\SelectStatementBuilder->build(Array)
\#3 /home/george/Projects/git/PHP-SQL-Parser/test.php(7): PHPSQLParser\PHPSQLCreator->create(Array)
\#4 {main}
  thrown in /home/george/Projects/git/PHP-SQL-Parser/src/PHPSQLParser/builders/OrderByBuilder.php on line 100

This is testing against the master branch of the git repository

_Original issue: http://code.google.com/p/php-sql-parser/issues/detail?id=141_

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on May 23, 2014 06:25:25_

I have added some code in r1359 to handle that.

**Status:** Fixed  
  **Owner:** pho...@gmx.de
