### ISSUE TITLE
join with to_number in on clause

### ISSUE THREAD

**Issue by witchi** [greenlion/PHP-SQL-Parser#183]
_From [NBakerCa...@gmail.com](https://code.google.com/u/117297254251119288105/) on December 23, 2014 16:42:27_

What steps will reproduce the problem? 1. Have tables you can't change that incorrectly store numbers as strings
2. join those tables using the 'to_number' function in the on clause
3. parse sql What is the expected output? What do you see instead? I would expect the library to detect the function and column, or at the very least ignore the function and detect the columns being joined on. The error and slq are posted below. What version of the product are you using? On what operating system? This problem exists in version 20140108. We are using Ubuntu 9.04 ( yes they haven't updated us yet... ). I can test this on debian 7 from home if needed. Please provide any additional information below. SQL:
SELECT *
FROM SC_CATALOG_DETAIL_REG CD
INNER JOIN MASTER_ITEM_LOOKUP IL
ON to_number( CD.STYLE ) = to_number( IL.SKU_NUM )

ERROR:
Fatal error:  Uncaught exception 'UnableToCalculatePositionException' with message 'cannot calculate position of MASTER_ITEM_LOOKUP IL
  ON to_number( CD.STYLE ) = to_number( IL.SKU_NUM ) within  )' in /var/www/test_dir/PHP-SQL-Parser/src/positions/PositionCalculator.php:199
Stack trace:
\#0 /var/www/test_dir/PHP-SQL-Parser/src/positions/PositionCalculator.php(215): PositionCalculator->lookForBaseExpression('SELECT *?  FROM...', 126, Array, 1, Array)
\#1 /var/www/test_dir/PHP-SQL-Parser/src/positions/PositionCalculator.php(215): PositionCalculator->lookForBaseExpression('SELECT *?  FROM...', 126, Array, 'FROM', Array)
\#2 /var/www/test_dir/PHP-SQL-Parser/src/positions/PositionCalculator.php(70): PositionCalculator->lookForBaseExpression('SELECT *?  FROM...', 126, Array, 0, Array)
\#3 /var/www/test_dir/PHP-SQL-Parser/src/PHPSQLParser.php(90): PositionCalculator->setPositionsWithinSQL('SELECT *?  FROM...', Array)
\#4 /var/www/test_dir/PHP-SQL-Parser/src/PHPSQLParser.php(65): PHPSQLParser->parse('SELECT *?  FROM...', true)
\#5 /var in /var/www/test_dir/PHP-SQL-Parser/src/positions/PositionCalculator.php on line 199

_Original issue: http://code.google.com/p/php-sql-parser/issues/detail?id=157_

**Comment by witchi** [comment]
_From [NBakerCa...@gmail.com](https://code.google.com/u/117297254251119288105/) on December 23, 2014 09:11:53_

I did leave out that this is being used within oracle. I did overlook that this is geared towards mysql.

**Comment by witchi** [comment]
Yes, to_number is Oracle dialect, so you could try to add the function name to the customFunctions with PHPSQLParserConstants->addCustomFunction('to_number').

**Comment by witchi** [comment]
I have added a test case for that issue and no error occurs.

**Comment by witchi** [comment]
Oops, I have enabled the PositionCalculator and there is still an error. I'll look deeper.

**Comment by witchi** [comment]
There must be an additional backtracking for custom functions. Now it should work.
