### ISSUE TITLE
=? unsupported

### ISSUE THREAD

**Issue by witchi** [greenlion/PHP-SQL-Parser#94]
_From [fxmul...@gmail.com](https://code.google.com/u/113665800341507414725/) on July 31, 2012 17:41:33_

The following query returns the following exception:

SELECT a.`admin_id` FROM admins a WHERE a.admin_username=? AND a.admin_password=?

PHP Fatal error:  Uncaught exception 'UnableToCalculatePositionException' with message 'cannot calculate position of = within  =? AND a.admin_password =?' in /var/www/apidev/trunk/sql/phpsqlparser.php:2023
Stack trace:
\#0 /var/www/apidev/trunk/sql/phpsqlparser.php(2039): PositionCalculator->lookForBaseExpression('SELECT a.`admin...', 56, Array, 1, Array)
\#1 /var/www/apidev/trunk/sql/phpsqlparser.php(2039): PositionCalculator->lookForBaseExpression('SELECT a.`admin...', 56, Array, 'WHERE', Array)
\#2 /var/www/apidev/trunk/sql/phpsqlparser.php(1910): PositionCalculator->lookForBaseExpression('SELECT a.`admin...', 56, Array, 0, Array)
\#3 /var/www/apidev/trunk/sql/phpsqlparser.php(496): PositionCalculator->setPositionsWithinSQL('SELECT a.`admin...', Array)
\#4 /var/www/apidev/trunk/sql/phpsqlparser.php(475): PHPSQLParser->parse('SELECT a.`admin...', true)
\#5 /var/www/apidev/trunk/test.php(6): PHPSQLParser->__construct('SELECT a.`admin...', true)

The query works if it is changed to:

SELECT a.`admin_id` FROM admins a WHERE a.admin_username= ? AND a.admin_password= ?

This is on 20120703

_Original issue: http://code.google.com/p/php-sql-parser/issues/detail?id=68_

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on August 08, 2012 12:15:29_

Did you ask Scully for a rational solution?

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on August 08, 2012 13:25:43_

This problem occurs, because the position calculator awaits some valid characters after an operator. I have added the question mark as such a character on REV 297.

**Status:** Accepted  
  **Owner:** pho...@gmx.de

**Comment by witchi** [comment]
_From [pho...@gmx.de](https://code.google.com/u/109317404671582518013/) on August 17, 2012 02:26:58_

**Status:** Fixed
